#!/bin/bash

# Install RightScale's RightLink package.

declare version

if [ "${arch}" = "i386" ]
then
    version="${RIGHTSCALE_VERSION:-5.7.16}"
else
    version="${RIGHTSCALE_VERSION:-5.8.8}"
fi

declare -r deb="rightscale_${version}-ubuntu_10.04-${arch}.deb"
declare -r url="http://mirror.rightscale.com/rightscale_rightlink/${version}/ubuntu/${deb}"
declare -r tmp_dir="/tmp"
declare -r sha512_file="$(readlink -f ${taskdir}/SHA512SUMS)"
declare deb_md5

wget -q -P "${imagedir}/${tmp_dir}" "${url}"

if [ -f "${imagedir}/${tmp_dir}/${deb}" ]
then
    grep -q -m 1 "${deb}" "${sha512_file}"
    if [ "${?}" -ne 0 ]
    then
	log "No known checksum for ${version}. Skipping check."
    else
	cd "${imagedir}/${tmp_dir}"
	if ! grep -m 1 "${deb}" "${sha512_file}" | \
            sed -e 's/\ \ .*\(rightscale_.*\)/\ \ \1/' | \
            sha512sum --quiet -c -
	then
            die "Error: ${deb} corrupted!"
	fi
	cd -
    fi
else
    die "Error: Failed to download '${deb}'."
fi

chroot "${imagedir}" "dpkg -i ${tmp_dir}/${deb}"
rm -f "${imagedir}/${tmp_dir}/${deb}"
