#!/bin/bash

# Install RightScale's RightLink package.
declare -r version="5.8.8"
declare -r deb="rightscale_${version}-ubuntu_10.04-amd64.deb"
declare -r deb_md5="ee2688aef7512d119ff117b200565e0f"
declare -r url="http://mirror.rightscale.com/rightscale_rightlink/${version}/ubuntu/${deb}"
declare -r tmp_dir="/tmp"

wget -P "${imagedir}/${tmp_dir}" "${url}"

if [ -f "${imagedir}/${tmp_dir}/${deb}" ]
then
    cd "${imagedir}/${tmp_dir}"
    if ! echo "${deb_md5}  ${imagedir}/${tmp_dir}/${deb}" | \
        md5sum --quiet -c -; then
    then
        die "Error: ${deb} corrupted!"
    fi
else
    die "Error: Failed to download '${deb}'."
fi

chroot "${imagedir}" "dpkg -i ${tmp_dir}/${deb}"
rm -f "${imagedir}/${tmp_dir}/${deb}"
